/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ammar Dzakwan
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        //Dzakwan : "bikin di awal muncul di tengah."
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BungkusButton = new java.awt.Button();
        DineInButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BungkusButton.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        BungkusButton.setForeground(new java.awt.Color(51, 51, 51));
        BungkusButton.setLabel("Bungkus");
        BungkusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BungkusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BungkusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 130, 30));

        DineInButton.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        DineInButton.setForeground(new java.awt.Color(51, 51, 51));
        DineInButton.setLabel("Dine In");
        DineInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DineInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DineInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 110, 30));

        jLabel1.setBackground(null);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projecctuasdpa/MenuUtamaPadangResto.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BungkusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BungkusButtonActionPerformed
       
        //Button Bungkus pindah frame + simpan var bungkus
        int MakanDmn = 2;
        
        FrameDineIn fdi = new FrameDineIn(MakanDmn);
        fdi.setLocationRelativeTo(null);
        fdi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BungkusButtonActionPerformed

    private void DineInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DineInButtonActionPerformed
       
        //Button Dine In pindah frame + simpan var Dine In
        int MakanDmn = 1;
        
        FrameDineIn fdi = new FrameDineIn(MakanDmn);
        fdi.setLocationRelativeTo(null);
        fdi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DineInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Frame1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button BungkusButton;
    private java.awt.Button DineInButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
